{\rtf1\ansi\ansicpg936\cocoartf1561\cocoasubrtf600
{\fonttbl\f0\fswiss\fcharset0 Helvetica;\f1\fnil\fcharset134 PingFangSC-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red251\green0\blue7;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;\cssrgb\c100000\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl320\sa240\partightenfactor0

\f0\fs28 \cf2 \expnd0\expndtw0\kerning0
spring: 
\fs24 \

\fs28 \'a0 profiles: 
\fs24 \

\fs28 \'a0\'a0\'a0 active: 
\fs24 \

\fs28 \'a0\'a0\'a0 - dev 
\fs24 \

\fs28 --- 
\fs24 \

\fs28 spring: 
\fs24 \
\pard\pardeftab720\sl320\sa240\partightenfactor0

\fs28 \cf3 \'a0 profiles: dev\'a0\'a0\'a0\'a0\'a0#
\f1 \'bf\'aa\'b7\'a2\'bb\'b7\'be\'b3
\f0  
\fs24 \cf2 \
\pard\pardeftab720\sl320\sa240\partightenfactor0

\fs28 \cf2 \'a0 application:\'a0 
\fs24 \

\fs28 \'a0\'a0\'a0 name: springcloud-config-lxh-dev 
\fs24 \

\fs28 --- 
\fs24 \

\fs28 spring: 
\fs24 \
\pard\pardeftab720\sl320\sa240\partightenfactor0

\fs28 \cf3 \'a0 profiles: test\'a0\'a0 #
\f1 \'b2\'e2\'ca\'d4\'bb\'b7\'be\'b3
\f0  
\fs24 \cf2 \
\pard\pardeftab720\sl320\sa240\partightenfactor0

\fs28 \cf2 \'a0 application:\'a0 
\fs24 \

\fs28 \'a0\'a0\'a0 name: springcloud-config-lxh-test 
\fs24 \
\pard\pardeftab720\sl320\sa240\partightenfactor0

\fs28 \cf3 #\'a0\'a0
\f1 \'c7\'eb\'b1\'a3\'b4\'e6\'ce\'aa
\f0 UTF-8
\f1 \'b8\'f1\'ca\'bd
\f0  }